export const ADD = 'ADD';
export const SUB = 'SUB';
export const GET_MOVIES = 'GET_MOVIES';

export const LOADING = 'LOADING';
export const UPDATESTATUSUSER = 'UPDATESTATUSUSER';
export const UPDATEREADYPROVIDER = 'UPDATEREADYPROVIDER';
export const UPDATEREADYPROVIDERREF = 'UPDATEREADYPROVIDERREF';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const GET_LIST_PRODUCT = 'GET_LIST_PRODUCT';
export const GET_LIST_PRODUCT_SUCCESS = 'GET_LIST_PRODUCT_SUCCESS';
export const GET_LIST_PRODUCT_FAIL = 'GET_LIST_PRODUCT_FAIL';

export const GET_FAVORITE_FOODS = 'GET_FAVORITE_FOODS';
export const GET_FAVORITE_FOODS_SUCCESS = 'GET_FAVORITE_FOODS_SUCCESS';
export const GET_FAVORITE_FOODS_FAIL = 'GET_FAVORITE_FOODS_FAIL';

export const GET_FOOD_DETAIL = 'GET_FOOD_DETAIL';
export const GET_FOOD_DETAIL_SUCCESS = 'GET_FOOD_DETAIL_SUCCESS';
export const GET_FOOD_DETAIL_FAIL = 'GET_FOOD_DETAIL_FAIL';

export const CREATE_FOOD = 'CREATE_FOOD';
export const CREATE_FOOD_SUCCESS = 'CREATE_FOOD_SUCCESS';
export const CREATE_FOOD_FAIL = 'CREATE_FOOD_FAIL';

export const SET_USER_INFO = 'SET_USER_INFO';

export const TOGGLE_MODAL_UPDATE_PROFILE = 'TOGGLE_MODAL_UPDATE_PROFILE';